// Dataset metadata per le 42 URL del sito.
// Editato a mano da Antonio (autore) — `og:image` rimanda a immagini reali
// quando note, altrimenti alla cover del libro come fallback.

export const SITE = {
  origin: 'https://cyberleo.it',
  name: 'CyberLeo',
  defaultImage: 'https://cyberleo.it/images/book/cover.jpg',
  defaultImageWidth: 1200,
  defaultImageHeight: 1800,
  brandTitle: 'Le Avventure di CyberLeo',
  brandTagline: 'Storie per crescere sicuri nel CyberMondo',
  author: 'Antonio Pedoto',
};

const cover = SITE.defaultImage;
const img = (p) => `${SITE.origin}${p}`;

// type: 'website' | 'book' | 'article' | 'profile'
// Quando un personaggio/storia ha immagine dedicata, sostituire `image` col path corretto.
export const PAGES = [
  // ---- HOME ----
  {
    path: '/',
    type: 'website',
    title: 'Le Avventure di CyberLeo — Storie per crescere sicuri nel CyberMondo',
    description: 'Il libro illustrato di sicurezza digitale per bambini 7-10 anni. Nove storie con CyberLeo e i suoi quattro amici, più Lo Zainetto di CyberLeo: tre o quattro chiavi per ogni storia. Anteprime sonore gratuite + diploma di Custode personalizzato.',
    h1: 'Le Avventure di CyberLeo',
    intro: 'Il libro illustrato di sicurezza digitale per bambini 7-10 anni: nove storie con un leoncino dalla criniera di fibre ottiche e i suoi quattro amici.',
    image: cover,
  },

  // ---- LIBRO + AUTORE ----
  {
    path: '/libro',
    type: 'book',
    title: 'Il libro · Le Avventure di CyberLeo',
    description: 'Volume 1 — 159 pagine, 9 storie illustrate per bambini di 7-10 anni. Lo Zainetto di CyberLeo accompagna ogni storia con tre o quattro chiavi pratiche di sicurezza digitale.',
    h1: 'Il libro',
    intro: 'Le Avventure di CyberLeo — Volume 1: 9 storie illustrate per bambini di 7-10 anni con Lo Zainetto di CyberLeo a fine capitolo.',
    image: cover,
  },
  {
    path: '/autore',
    type: 'profile',
    title: 'Antonio Pedoto · L\'autore di CyberLeo',
    description: 'Antonio Pedoto, autore de Le Avventure di CyberLeo. Tecnologo, padre e narratore: porta la sicurezza digitale ai bambini con storie illustrate.',
    h1: 'L\'autore',
    intro: 'Antonio Pedoto — autore de Le Avventure di CyberLeo.',
    image: cover,
  },

  // ---- ANTEPRIME SONORE ----
  {
    path: '/anteprime',
    type: 'website',
    title: 'Anteprime sonore · Le Avventure di CyberLeo',
    description: 'Ascolta gratuitamente le anteprime sonore delle nove storie di CyberLeo. Voci narranti, effetti e musiche per immergerti nel CyberMondo prima di leggere il libro.',
    h1: 'Anteprime sonore',
    intro: 'Le anteprime audio gratuite delle nove storie di CyberLeo.',
    image: cover,
  },
  {
    path: '/anteprime/a-te-che-stai-per-leggere',
    type: 'article',
    title: 'A te che stai per leggere · CyberLeo (anteprima)',
    description: 'La lettera di apertura del libro: a te che stai per leggere e diventare un piccolo Custode del CyberMondo.',
    h1: 'A te che stai per leggere',
    intro: 'La lettera di apertura del libro di CyberLeo.',
    image: cover,
  },
  {
    path: '/anteprime/come-e-nato-il-cybermondo',
    type: 'article',
    title: 'Come è nato il CyberMondo · CyberLeo (anteprima)',
    description: 'L\'origine del CyberMondo: un racconto-prologo per scoprire dove vivono CyberLeo e i suoi amici.',
    h1: 'Come è nato il CyberMondo',
    intro: 'L\'origine del CyberMondo, il prologo della saga.',
    image: cover,
  },
  {
    path: '/anteprime/il-diario-di-miko',
    type: 'article',
    title: 'Il diario di Miko · CyberLeo (anteprima)',
    description: 'Una storia di Le Avventure di CyberLeo: il diario di Miko e cosa succede quando un quaderno digitale finisce nelle mani sbagliate.',
    h1: 'Il diario di Miko',
    intro: 'Storia sul diario digitale e su come custodire i propri pensieri privati.',
    image: cover,
  },
  {
    path: '/anteprime/la-casa-dei-messaggi',
    type: 'article',
    title: 'La casa dei messaggi · CyberLeo (anteprima)',
    description: 'Una storia di Le Avventure di CyberLeo dedicata alle chat sicure: cosa scrivere, a chi, e quando spegnere.',
    h1: 'La casa dei messaggi',
    intro: 'La storia che insegna ai bambini come abitare la chat in modo sicuro.',
    image: cover,
  },
  {
    path: '/anteprime/la-busta-troppo-gentile',
    type: 'article',
    title: 'La busta troppo gentile · CyberLeo (anteprima)',
    description: 'Una storia di Le Avventure di CyberLeo sul phishing: quando una busta sembra troppo gentile per essere vera, di solito non lo è.',
    h1: 'La busta troppo gentile',
    intro: 'La storia di CyberLeo che spiega il phishing ai bambini con un\'allegoria.',
    image: cover,
  },
  {
    path: '/anteprime/le-sentinelle-silenziose',
    type: 'article',
    title: 'Le sentinelle silenziose · CyberLeo (anteprima)',
    description: 'Una storia di Le Avventure di CyberLeo: gli antivirus, i filtri e le piccole guardie invisibili che proteggono il CyberMondo.',
    h1: 'Le sentinelle silenziose',
    intro: 'Le sentinelle che proteggono il CyberMondo senza farsi vedere.',
    image: cover,
  },
  {
    path: '/anteprime/le-sfere-ricordo-di-pixel',
    type: 'article',
    title: 'Le sfere-ricordo di Pixel · CyberLeo (anteprima)',
    description: 'Una storia di Le Avventure di CyberLeo: i ricordi digitali di Pixel e cosa significa "fare un backup" quando hai sette anni.',
    h1: 'Le sfere-ricordo di Pixel',
    intro: 'La storia del backup raccontata attraverso le sfere-ricordo di Pixel.',
    image: cover,
  },
  {
    path: '/anteprime/la-torre-dei-libri',
    type: 'article',
    title: 'La torre dei libri · CyberLeo (anteprima)',
    description: 'Una storia di Le Avventure di CyberLeo sul diritto d\'autore e la condivisione responsabile dei contenuti.',
    h1: 'La torre dei libri',
    intro: 'La storia che insegna ai bambini il valore di ciò che è stato creato.',
    image: cover,
  },
  {
    path: '/anteprime/la-fontana-che-canta',
    type: 'article',
    title: 'La fontana che canta · CyberLeo (anteprima)',
    description: 'Una storia di Le Avventure di CyberLeo: musica, streaming, condivisione e il rispetto di chi crea.',
    h1: 'La fontana che canta',
    intro: 'La fontana che canta e cosa significa ascoltare con rispetto.',
    image: cover,
  },
  {
    path: '/anteprime/la-chiavetta-trovata',
    type: 'article',
    title: 'La chiavetta trovata · CyberLeo (anteprima)',
    description: 'Una storia di Le Avventure di CyberLeo: cosa succede quando trovi un dispositivo che non è tuo. Curiosità, pericolo, scelta giusta.',
    h1: 'La chiavetta trovata',
    intro: 'Una chiavetta USB trovata per terra: la storia che insegna la cautela.',
    image: cover,
  },
  {
    path: '/anteprime/la-notte-in-piazza',
    type: 'article',
    title: 'La notte in piazza · CyberLeo (anteprima)',
    description: 'Una storia di Le Avventure di CyberLeo: le reti pubbliche, gli incontri inattesi e l\'importanza di stare insieme nel CyberMondo.',
    h1: 'La notte in piazza',
    intro: 'Cosa accade nel CyberMondo durante la notte in piazza.',
    image: cover,
  },

  // ---- SEI DIFESE ----
  {
    path: '/sei-difese',
    type: 'website',
    title: 'Le sei difese · CyberLeo',
    description: 'Le sei difese che ogni piccolo Custode del CyberMondo impara con CyberLeo: identità, doppia chiave, attenzione, sentinelle, ricordi, insieme.',
    h1: 'Le sei difese del CyberMondo',
    intro: 'Sei pilastri di sicurezza digitale per bambini, raccontati come amici.',
    image: cover,
  },
  {
    path: '/sei-difese/chi-siamo-noi',
    type: 'article',
    title: 'Chi siamo noi · Le sei difese di CyberLeo',
    description: 'La prima difesa: sapere chi sei e proteggere la tua identità online. Nome, età, scuola, foto: cosa si dice e cosa no.',
    h1: 'Chi siamo noi',
    intro: 'La prima difesa di CyberLeo: la propria identità.',
    image: cover,
  },
  {
    path: '/sei-difese/doppia-chiave',
    type: 'article',
    title: 'Doppia chiave · Le sei difese di CyberLeo',
    description: 'La seconda difesa: password robuste e doppia chiave (autenticazione a due fattori) spiegate ai bambini.',
    h1: 'Doppia chiave',
    intro: 'Password forti e doppia chiave per i piccoli Custodi.',
    image: cover,
  },
  {
    path: '/sei-difese/attenzione-bugie',
    type: 'article',
    title: 'Attenzione alle bugie · Le sei difese di CyberLeo',
    description: 'La terza difesa: riconoscere il phishing, le truffe e le notizie false. Imparare a dubitare con gentilezza.',
    h1: 'Attenzione alle bugie',
    intro: 'Phishing e fake news raccontati ai bambini.',
    image: cover,
  },
  {
    path: '/sei-difese/sentinelle',
    type: 'article',
    title: 'Sentinelle · Le sei difese di CyberLeo',
    description: 'La quarta difesa: antivirus, filtri, parental control e tutte le sentinelle silenziose che ci proteggono.',
    h1: 'Sentinelle',
    intro: 'Le piccole guardie invisibili del CyberMondo.',
    image: cover,
  },
  {
    path: '/sei-difese/ricordi-al-sicuro',
    type: 'article',
    title: 'Ricordi al sicuro · Le sei difese di CyberLeo',
    description: 'La quinta difesa: backup, copie e privacy. Mettere al sicuro i propri ricordi digitali.',
    h1: 'Ricordi al sicuro',
    intro: 'Backup e privacy spiegati con le sfere-ricordo.',
    image: cover,
  },
  {
    path: '/sei-difese/insieme',
    type: 'article',
    title: 'Insieme · Le sei difese di CyberLeo',
    description: 'La sesta difesa: chiedere aiuto, fidarsi degli adulti, stare con gli altri. La sicurezza più grande è non essere soli.',
    h1: 'Insieme',
    intro: 'La sicurezza più grande è non essere soli.',
    image: cover,
  },

  // ---- PERSONAGGI ----
  {
    path: '/personaggi',
    type: 'website',
    title: 'I personaggi · Le Avventure di CyberLeo',
    description: 'Tutti i personaggi del CyberMondo: CyberLeo, Lunabyte, Miko, Pixel, Spark, Iride, Nonno Ottavio e i tre antagonisti FakeFox, Virus Vex, ShadowGlitch.',
    h1: 'I personaggi del CyberMondo',
    intro: 'Eroi e antagonisti del CyberMondo.',
    image: cover,
  },
  {
    path: '/personaggi/cyberleo',
    type: 'profile',
    title: 'CyberLeo · Il leoncino dalla criniera di fibre ottiche',
    description: 'CyberLeo è il piccolo eroe del CyberMondo: un leoncino dalla criniera di fibre ottiche che insegna ai bambini come difendersi online con coraggio e gentilezza.',
    h1: 'CyberLeo',
    intro: 'Il leoncino dalla criniera di fibre ottiche, protagonista della saga.',
    image: img('/images/heroes/cyberleo.jpg'),
  },
  {
    path: '/personaggi/lunabyte',
    type: 'profile',
    title: 'Lunabyte · Personaggio di CyberLeo',
    description: 'Lunabyte è una delle amiche di CyberLeo nel CyberMondo. Scopri il suo ruolo nelle storie del libro.',
    h1: 'Lunabyte',
    intro: 'Una delle amiche di CyberLeo nel CyberMondo.',
    image: img('/images/heroes/lunabyte.jpg'),
  },
  {
    path: '/personaggi/miko',
    type: 'profile',
    title: 'Miko · Personaggio di CyberLeo',
    description: 'Miko è uno degli amici di CyberLeo. Il suo diario digitale è al centro di una delle nove storie del libro.',
    h1: 'Miko',
    intro: 'L\'amico di CyberLeo che tiene un diario digitale.',
    image: img('/images/heroes/miko.jpg'),
  },
  {
    path: '/personaggi/pixel',
    type: 'profile',
    title: 'Pixel · Personaggio di CyberLeo',
    description: 'Pixel è l\'amica di CyberLeo che custodisce le sfere-ricordo: la storia che insegna ai bambini il valore dei backup.',
    h1: 'Pixel',
    intro: 'La piccola custode delle sfere-ricordo nel CyberMondo.',
    image: img('/images/heroes/pixel.jpg'),
  },
  {
    path: '/personaggi/spark',
    type: 'profile',
    title: 'Spark · Personaggio di CyberLeo',
    description: 'Spark è uno degli amici di CyberLeo. Scintilla, energia, coraggio: il suo ruolo nelle storie del CyberMondo.',
    h1: 'Spark',
    intro: 'L\'amico-scintilla di CyberLeo.',
    image: img('/images/heroes/spark.jpg'),
  },
  {
    path: '/personaggi/iride',
    type: 'profile',
    title: 'Iride · Personaggio di CyberLeo',
    description: 'Iride è uno dei personaggi del CyberMondo. Colori, prismi e diversità nelle storie de Le Avventure di CyberLeo.',
    h1: 'Iride',
    intro: 'Il personaggio dai colori del CyberMondo.',
    image: img('/images/heroes/iride.jpg'),
  },
  {
    path: '/personaggi/nonno-ottavio',
    type: 'profile',
    title: 'Nonno Ottavio · Personaggio di CyberLeo',
    description: 'Nonno Ottavio è la voce della memoria nel CyberMondo. Il suo sguardo ponte tra il mondo prima della rete e quello di oggi.',
    h1: 'Nonno Ottavio',
    intro: 'La voce della memoria del CyberMondo.',
    image: img('/images/heroes/nonno-ottavio.jpg'),
  },
  {
    path: '/personaggi/fakefox',
    type: 'profile',
    title: 'FakeFox · L\'antagonista di CyberLeo',
    description: 'FakeFox è uno dei tre antagonisti del CyberMondo: la volpe delle bugie, simbolo del phishing e degli inganni online.',
    h1: 'FakeFox',
    intro: 'La volpe delle bugie del CyberMondo: il phishing.',
    image: img('/images/characters/fakefox.jpg'),
  },
  {
    path: '/personaggi/virus-vex',
    type: 'profile',
    title: 'Virus Vex · L\'antagonista di CyberLeo',
    description: 'Virus Vex è uno dei tre antagonisti del CyberMondo: rappresenta i virus, i malware e tutto ciò che danneggia in silenzio.',
    h1: 'Virus Vex',
    intro: 'L\'antagonista che porta i malware nel CyberMondo.',
    image: img('/images/characters/virus-vex.jpg'),
  },
  {
    path: '/personaggi/shadowglitch',
    type: 'profile',
    title: 'ShadowGlitch · L\'antagonista di CyberLeo',
    description: 'ShadowGlitch è il terzo antagonista del CyberMondo: l\'ombra che fa sparire i dati e confonde i ricordi.',
    h1: 'ShadowGlitch',
    intro: 'L\'ombra-glitch che confonde i ricordi del CyberMondo.',
    image: img('/images/characters/shadowglitch.jpg'),
  },

  // ---- RISORSE ----
  {
    path: '/patto',
    type: 'article',
    title: 'Il patto del piccolo Custode · CyberLeo',
    description: 'Il patto che ogni piccolo lettore firma a metà libro: le regole del CyberMondo dette con parole semplici, una mano e un sorriso.',
    h1: 'Il patto del piccolo Custode',
    intro: 'Le regole del CyberMondo, dette con parole semplici.',
    image: cover,
  },
  {
    path: '/diploma',
    type: 'article',
    title: 'Diploma di Custode · CyberLeo',
    description: 'A fine libro ogni bambino diventa un piccolo Custode del CyberMondo e riceve il suo diploma personalizzato. Scaricalo qui dopo aver completato il percorso.',
    h1: 'Diploma di Custode',
    intro: 'Il diploma personalizzato per i piccoli Custodi del CyberMondo.',
    image: cover,
  },
  {
    path: '/glossarietto',
    type: 'article',
    title: 'Glossarietto · Le parole del CyberMondo',
    description: 'Le parole della sicurezza digitale spiegate ai bambini: phishing, password, backup, antivirus, account. Da sfogliare insieme.',
    h1: 'Glossarietto',
    intro: 'Le parole della sicurezza digitale, spiegate ai bambini.',
    image: cover,
  },
  {
    path: '/vol2',
    type: 'website',
    title: 'Volume 2 · Le Avventure di CyberLeo',
    description: 'Il secondo volume de Le Avventure di CyberLeo è in lavorazione. Iscriviti per ricevere news in anteprima e suggerire nuove storie.',
    h1: 'Volume 2 in arrivo',
    intro: 'Il secondo volume è in lavorazione.',
    image: cover,
  },
  {
    path: '/genitori',
    type: 'article',
    title: 'Per i genitori · CyberLeo',
    description: 'Una guida per i genitori: come usare Le Avventure di CyberLeo a casa, domande da fare, attività per ogni storia. Niente paura, solo dialogo.',
    h1: 'Per i genitori',
    intro: 'Come accompagnare i bambini nel CyberMondo, a casa.',
    image: cover,
  },
  {
    path: '/insegnanti',
    type: 'article',
    title: 'Per gli insegnanti · CyberLeo',
    description: 'Una guida per gli insegnanti della scuola primaria: schede operative, obiettivi didattici e laboratori per ogni storia di CyberLeo.',
    h1: 'Per gli insegnanti',
    intro: 'Schede operative e laboratori per la scuola primaria.',
    image: cover,
  },
  {
    path: '/avventure',
    type: 'website',
    title: 'Tutte le avventure · CyberLeo',
    description: 'L\'elenco completo delle avventure del CyberMondo: nove storie + intro + epilogo, ognuna con la sua chiave di sicurezza digitale.',
    h1: 'Tutte le avventure',
    intro: 'L\'indice completo delle storie del CyberMondo.',
    image: cover,
  },
  {
    path: '/video',
    type: 'website',
    title: 'Video · CyberLeo',
    description: 'Trailer, letture animate e clip dal CyberMondo: i video ufficiali de Le Avventure di CyberLeo.',
    h1: 'Video',
    intro: 'Trailer e letture animate dal CyberMondo.',
    image: cover,
  },
  {
    path: '/privacy',
    type: 'article',
    title: 'Privacy · CyberLeo',
    description: 'Informativa privacy e cookie del sito cyberleo.it. Niente tracker invadenti, niente foto dei bambini condivise senza consenso.',
    h1: 'Privacy',
    intro: 'Informativa privacy e cookie.',
    image: cover,
  },
];
